################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.c \
C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.c 

OBJS += \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_cortex.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_dma.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ex.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ramfunc.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_gpio.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_i2c.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr_ex.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc_ex.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim_ex.o \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_uart.o 

C_DEPS += \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_cortex.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_dma.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ex.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ramfunc.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_gpio.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_i2c.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr_ex.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc_ex.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim_ex.d \
./Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_uart.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_cortex.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_dma.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ex.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ramfunc.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash_ramfunc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_gpio.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_i2c.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr_ex.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc_ex.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim_ex.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_uart.o: C:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L152xE -DDEBUG -c -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc -I../Core/Inc -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Include -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/STM32L1xx_HAL_Driver/Inc/Legacy -IC:/Users/Simon.Kupfer.ATS-INTRANET/STM32Cube/Repository/STM32Cube_FW_L1_V1.9.0/Drivers/CMSIS/Device/ST/STM32L1xx/Include -I"C:/Projekte/VL53L0XonSTM32_Test/Drivers/VL53L0X" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Inc" -I"C:/Projekte/VL53L0XonSTM32_Test/Core/Src" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32L1xx_HAL_Driver/stm32l1xx_hal_uart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

